version: "3.2"
services:
  postgres:
    image: postgres:latest
    network_mode: bridge
    container_name: postgres
    volumes:
      - ./init:/docker-entrypoint-initdb.d/
    expose:
      - 5432
    ports:
      - 5432:5432
    environment:
      - POSTGRES_PASSWORD=admin
      - POSTGRES_USER=postgres
      - POSTGRES_DB=testdb

    restart: unless-stopped
  # APP*****************************************
  springbootapp:
    image: gatewayapp:latest
    network_mode: bridge
    container_name: gatewayapp
    expose:
      - 8080
    ports:
      - 8080:8080
    restart: unless-stopped
    depends_on:
      - postgres
    links:
      - postgres
volumes:
  postgres-data:
